const LABELS = {
	customer: {
		search_customer: 'Search Customer',
		phone_number: 'Phone Number',
		customer_name: 'Customer Name',
		notes: 'Customer Notes',
	},
	employee: {
		username: 'Username',
		password: 'Password',
		retype_password: 'Retype Password',
		first_name: 'First Name',
		last_name: 'Last Name',
		gender: 'Gender',
		role: 'Role',
		permissions: 'Permissions',
		body_rate: 'Body Rate',
		feet_rate: 'Feet Rate',
		acupuncture_rate: 'Acupuncture Rate',
		per_hour: 'Hourly Rate',
	},
	profile: {
		language: 'Language',
		dark_mode: 'Dark Mode',
	},
	reservation: {
		date: 'Select Date',
		time: 'Select Time',
		employee_id: 'Select Employee',
		service_id: 'Select Service',
		requested_gender: 'Requested Gender',
		requested_employee: 'Requested Employee',
		cash: 'Cash',
		machine: 'Machine',
		vip: 'VIP',
		gift_card: 'Gift Card',
		insurance: 'Acupuncture Insurance',
		tip_method: 'Tip Method',
		tips: 'Tips',
		message: 'Message',
	},
	schedule: {
		start: 'Select Start Time',
		end: 'Select End Time',
		priority: 'Select Priority',
		is_working: 'Is Working',
		on_call: 'On Call',
		filter: 'Select Date',
	},
	service: {
		service_name: 'Service Name',
		shorthand: 'Shorthand',
		time: 'Time (Minutes)',
		money: 'Money',
		body: 'Body',
		feet: 'Feet',
		acupuncture: 'Acupuncture',
		beds_required: 'Beds Required',
		can_overlap: 'Can Overlap',
		color: 'Color',
	},
	vip_package: {
		serial: 'Serial',
		sold_amount: 'Sold Amount',
		commission_amount: 'Commission Amount',
		employee_ids: 'Employees',
	},
};

export default LABELS;
