const LABELS = {
	acupuncture_report: {
		acupuncture_percentage: 'Acupuncture Percentage',
		massage_percentage: 'Massage Percentage',
		insurance_percentage: 'Insurance Percentage',
		non_acupuncturist_insurance_percentage: 'Insurance Percentage (Other)',
	},
	customer: {
		search_customer: 'Search Customer',
		phone_number: 'Phone Number',
		vip_serial: 'VIP Serial',
		customer_name: 'Customer Name',
		notes: 'Customer Notes',
	},
	employee: {
		username: 'Username',
		password: 'Password',
		retype_password: 'Retype Password',
		first_name: 'First Name',
		last_name: 'Last Name',
		gender: 'Gender',
		role: 'Role',
		permissions: 'Permissions',
		body_rate: 'Body Rate',
		feet_rate: 'Feet Rate',
		acupuncture_rate: 'Acupuncture Rate',
		per_hour: 'Hourly Rate',
	},
	gift_card: {
		gift_card_id: 'Gift Card ID',
		date: 'Select Date',
		payment_method: 'Payment Method',
		payment_amount: 'Payment Amount',
	},
	payroll: {
		year: 'Year',
		month: 'Month',
		option: 'Option',
		cheque_amount: 'Cheque Amount',
	},
	profile: {
		language: 'Language',
		old_password: 'Old Password',
		new_password: 'New Password',
		retype_new_password: 'Retype New Password',
	},
	reservation: {
		date: 'Select Date',
		time: 'Select Time',
		employee_id: 'Select Employee',
		service_id: 'Select Service',
		requested_gender: 'Requested Gender',
		requested_employee: 'Requested Employee',
		cash: 'Cash',
		machine: 'Machine',
		vip: 'VIP',
		gift_card: 'Gift Card',
		insurance: 'Acupuncture Insurance',
		cash_out: 'Cash Out',
		tip_method: 'Tip Method',
		tips: 'Tips',
		message: 'Message',
	},
	schedule: {
		start: 'Select Start Time',
		end: 'Select End Time',
		priority: 'Select Priority',
		is_working: 'Is Working',
		on_call: 'On Call',
		add_award: 'Add Award',
		filter: 'Select Date',
	},
	service: {
		service_name: 'Service Name',
		shorthand: 'Shorthand',
		time: 'Time (Minutes)',
		money: 'Money',
		body: 'Body',
		feet: 'Feet',
		acupuncture: 'Acupuncture',
		beds_required: 'Beds Required',
		color: 'Color',
	},
	vip_package: {
		serial: 'Serial',
		sold_amount: 'Sold Amount',
		commission_amount: 'Commission Amount',
		employee_ids: 'Employees',
	},
};

export default LABELS;
